### ISSUE TITLE
Seems Bagginses is causing a random 'fatal'

### ISSUE THREAD

**Issue by xondk** [BreakfastCraft/Spilled-Juice-Modpack#56]
I am getting the following message quite often, it seems to coincide with client connected to the server stalls but doesn't crash, yet no one is using bagginses instead using the sacks, so why it happens is unknown.

---

[23:49:29] [Netty Epoll Server IO #8/INFO] [STDOUT]: [nl.lang2619.bagginses.helpers.Messages.OpenBagMessage$MyMessageHandler:onMessage:42]: Listening
[23:49:29] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at nl.lang2619.bagginses.helpers.Messages.OpenBagMessage$MyMessageHandler.handle(OpenBagMessage.java:50) ~[OpenBagMessage$MyMessageHandler.class:?]
        at nl.lang2619.bagginses.helpers.Messages.OpenBagMessage$MyMessageHandler.lambda$onMessage$0(OpenBagMessage.java:43) ~[OpenBagMessage$MyMessageHandler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more

**Comment by xondk** [comment]
Update: Could be because of overlapping key with other stuff, in this case overlapping with PSI mod, C button, meaning when toggling PSI main button, then it also triggers the bagginses mod?

**Comment by slidingmike** [comment]
Possibly. I haven't had any other reports about this. I'd recommend sending that log to the Bag dev and see if they offer any information.
