### ISSUE TITLE
Crash when starting. help!

### ISSUE THREAD

**Issue by SlashJay-8566** [BreakfastCraft/Spilled-Juice-Modpack#90]
spilledjuice crashes with this message:
[15/11/2017 20:10:28 PM] Exception in thread "Client thread" [20:10:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15/11/2017 20:10:28 PM] [20:10:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[15/11/2017 20:10:28 PM] [20:10:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[15/11/2017 20:10:28 PM] [20:10:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[15/11/2017 20:10:28 PM] [20:10:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[15/11/2017 20:10:28 PM] [20:10:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15/11/2017 20:10:28 PM] [20:10:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
any help here?

**Comment by topher2010** [comment]
New modpack being developed, this version is no longer supported.
