### ISSUE TITLE
issues loading game

### ISSUE THREAD

**Issue by Keyboardfish** [BreakfastCraft/Spilled-Juice-Modpack#91]
Hi! So, on first install this pack works perfectly. But when I try to play it a second time, it crashes. Re-installing seems to fix it, so I'm still playing, but it's a bit weird.

**Comment by Keyboardfish** [comment]
[28/3/2018 08:47:06 AM] 	at net.minecraft.block.Block.func_149671_p(SourceFile:1063) ~[akf.class:?]
[28/3/2018 08:47:06 AM] 	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:503) ~[kq.class:?]
[28/3/2018 08:47:06 AM] 	at net.minecraft.client.Minecraft.<init>(SourceFile:374) ~[bcx.class:?]
[28/3/2018 08:47:06 AM] 	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
[28/3/2018 08:47:06 AM] 	... 6 more
[28/3/2018 08:47:06 AM] Exception in thread "Client thread" [08:47:06] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[28/3/2018 08:47:06 AM] [08:47:06] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[28/3/2018 08:47:06 AM] [08:47:06] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[28/3/2018 08:47:06 AM] [08:47:06] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[28/3/2018 08:47:06 AM] [08:47:06] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[28/3/2018 08:47:06 AM] [08:47:06] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[28/3/2018 08:47:06 AM] [08:47:06] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

there's the log when everything starts going all red.

**Comment by topher2010** [comment]
New modpack being developed, this version is no longer supported.
